workflows:
  build-for-appetize:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build for iOS Simulator
        script: |
          flutter build ios --simulator
      - name: Zip the Runner.app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app
    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip