workflows:
  build-for-appetize:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Clean iOS build & remove Podfile
        script: |
          rm -f ios/Podfile ios/Podfile.lock
          rm -rf ios/Pods
          flutter clean
          flutter pub get

      - name: Update Homebrew and install CocoaPods
        script: |
          brew update
          brew install cocoapods

      - name: Regenerate Podfile without building
        script: |
          flutter precache
          flutter build ios --simulator --no-pub || true
          if [ -f ios/Podfile ]; then
            echo "===== Regenerated Podfile ====="
            cat ios/Podfile
          else
            echo "⚠️ Podfile was not regenerated."
            exit 1
          fi

      - name: Build for iOS Simulator
        script: |
          flutter build ios --simulator

      - name: Zip the Runner.app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
