// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCGS88fZEU0JCaAam_xDOwBN-cZiwfwVLk',
//     appId: '1:55777096357:web:04bf991eeb1784cf38934c',
//     messagingSenderId: '55777096357',
//     projectId: 'pulus-c32d9',
//     authDomain: 'pulus-c32d9.firebaseapp.com',
//     storageBucket: 'pulus-c32d9.firebasestorage.app',
//     measurementId: 'G-45NM1XM0JH',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCy2sbiOFg68Piib1zvGMoNE7itVpL8bkM',
//     appId: '1:55777096357:android:617aff6dab0b32e838934c',
//     messagingSenderId: '55777096357',
//     projectId: 'pulus-c32d9',
//     storageBucket: 'pulus-c32d9.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBlBpnR5gab974ZoctO7MO1ztr5bceeVU8',
//     appId: '1:55777096357:ios:cbd472577caa5e3638934c',
//     messagingSenderId: '55777096357',
//     projectId: 'pulus-c32d9',
//     storageBucket: 'pulus-c32d9.firebasestorage.app',
//     iosBundleId: 'com.pulus.puluspatient',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBlBpnR5gab974ZoctO7MO1ztr5bceeVU8',
//     appId: '1:55777096357:ios:cbd472577caa5e3638934c',
//     messagingSenderId: '55777096357',
//     projectId: 'pulus-c32d9',
//     storageBucket: 'pulus-c32d9.firebasestorage.app',
//     iosBundleId: 'com.pulus.puluspatient',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCGS88fZEU0JCaAam_xDOwBN-cZiwfwVLk',
//     appId: '1:55777096357:web:7217eeab05f010a438934c',
//     messagingSenderId: '55777096357',
//     projectId: 'pulus-c32d9',
//     authDomain: 'pulus-c32d9.firebaseapp.com',
//     storageBucket: 'pulus-c32d9.firebasestorage.app',
//     measurementId: 'G-KVKK56S6JZ',
//   );
// }
